/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddCustomerRouteImport } from './routes/add-customer'
import { Route as AdhocVisitsRouteImport } from './routes/adhoc-visits'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as CityManagementRouteImport } from './routes/city-management'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataImportRouteImport } from './routes/data-import'
import { Route as ExportDataRouteImport } from './routes/export-data'
import { Route as LiveActivityRouteImport } from './routes/live-activity'
import { Route as LiveLocationRouteImport } from './routes/live-location'
import { Route as LiveShiftsRouteImport } from './routes/live-shifts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissedVisitsRouteImport } from './routes/missed-visits'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RunSchedulersRouteImport } from './routes/run-schedulers'
import { Route as SalesTeamRouteImport } from './routes/sales-team'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShiftRouteImport } from './routes/shift'
import { Route as SupportTicketsRouteImport } from './routes/support-tickets'
import { Route as CustomerIdRouteImport } from './routes/customer.$id'
import { Route as OfficerIdRouteImport } from './routes/officer.$id'
import { Route as VisitsIndexRouteImport } from './routes/visits.index'
import { Route as VisitsIdRouteImport } from './routes/visits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCustomerRoute = AddCustomerRouteImport.update({
  id: '/add-customer',
  path: '/add-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdhocVisitsRoute = AdhocVisitsRouteImport.update({
  id: '/adhoc-visits',
  path: '/adhoc-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CityManagementRoute = CityManagementRouteImport.update({
  id: '/city-management',
  path: '/city-management',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataImportRoute = DataImportRouteImport.update({
  id: '/data-import',
  path: '/data-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportDataRoute = ExportDataRouteImport.update({
  id: '/export-data',
  path: '/export-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveActivityRoute = LiveActivityRouteImport.update({
  id: '/live-activity',
  path: '/live-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLocationRoute = LiveLocationRouteImport.update({
  id: '/live-location',
  path: '/live-location',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveShiftsRoute = LiveShiftsRouteImport.update({
  id: '/live-shifts',
  path: '/live-shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissedVisitsRoute = MissedVisitsRouteImport.update({
  id: '/missed-visits',
  path: '/missed-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RunSchedulersRoute = RunSchedulersRouteImport.update({
  id: '/run-schedulers',
  path: '/run-schedulers',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTeamRoute = SalesTeamRouteImport.update({
  id: '/sales-team',
  path: '/sales-team',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftRoute = ShiftRouteImport.update({
  id: '/shift',
  path: '/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTicketsRoute = SupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIdRoute = CustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIdRoute = OfficerIdRouteImport.update({
  id: '/officer/$id',
  path: '/officer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsIndexRoute = VisitsIndexRouteImport.update({
  id: '/visits/',
  path: '/visits/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsIdRoute = VisitsIdRouteImport.update({
  id: '/visits/$id',
  path: '/visits/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-customer': typeof AddCustomerRoute
  '/adhoc-visits': typeof AdhocVisitsRoute
  '/attendance': typeof AttendanceRoute
  '/city-management': typeof CityManagementRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/data-import': typeof DataImportRoute
  '/export-data': typeof ExportDataRoute
  '/live-activity': typeof LiveActivityRoute
  '/live-location': typeof LiveLocationRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/login': typeof LoginRoute
  '/missed-visits': typeof MissedVisitsRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/run-schedulers': typeof RunSchedulersRoute
  '/sales-team': typeof SalesTeamRoute
  '/samples': typeof SamplesRoute
  '/settings': typeof SettingsRoute
  '/shift': typeof ShiftRoute
  '/support-tickets': typeof SupportTicketsRoute
  '/customer/$id': typeof CustomerIdRoute
  '/officer/$id': typeof OfficerIdRoute
  '/visits/$id': typeof VisitsIdRoute
  '/visits/': typeof VisitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-customer': typeof AddCustomerRoute
  '/adhoc-visits': typeof AdhocVisitsRoute
  '/attendance': typeof AttendanceRoute
  '/city-management': typeof CityManagementRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/data-import': typeof DataImportRoute
  '/export-data': typeof ExportDataRoute
  '/live-activity': typeof LiveActivityRoute
  '/live-location': typeof LiveLocationRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/login': typeof LoginRoute
  '/missed-visits': typeof MissedVisitsRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/run-schedulers': typeof RunSchedulersRoute
  '/sales-team': typeof SalesTeamRoute
  '/samples': typeof SamplesRoute
  '/settings': typeof SettingsRoute
  '/shift': typeof ShiftRoute
  '/support-tickets': typeof SupportTicketsRoute
  '/customer/$id': typeof CustomerIdRoute
  '/officer/$id': typeof OfficerIdRoute
  '/visits/$id': typeof VisitsIdRoute
  '/visits': typeof VisitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-customer': typeof AddCustomerRoute
  '/adhoc-visits': typeof AdhocVisitsRoute
  '/attendance': typeof AttendanceRoute
  '/city-management': typeof CityManagementRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/data-import': typeof DataImportRoute
  '/export-data': typeof ExportDataRoute
  '/live-activity': typeof LiveActivityRoute
  '/live-location': typeof LiveLocationRoute
  '/live-shifts': typeof LiveShiftsRoute
  '/login': typeof LoginRoute
  '/missed-visits': typeof MissedVisitsRoute
  '/notifications': typeof NotificationsRoute
  '/payroll': typeof PayrollRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/run-schedulers': typeof RunSchedulersRoute
  '/sales-team': typeof SalesTeamRoute
  '/samples': typeof SamplesRoute
  '/settings': typeof SettingsRoute
  '/shift': typeof ShiftRoute
  '/support-tickets': typeof SupportTicketsRoute
  '/customer/$id': typeof CustomerIdRoute
  '/officer/$id': typeof OfficerIdRoute
  '/visits/$id': typeof VisitsIdRoute
  '/visits/': typeof VisitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-customer'
    | '/adhoc-visits'
    | '/attendance'
    | '/city-management'
    | '/customers'
    | '/dashboard'
    | '/data-import'
    | '/export-data'
    | '/live-activity'
    | '/live-location'
    | '/live-shifts'
    | '/login'
    | '/missed-visits'
    | '/notifications'
    | '/payroll'
    | '/products'
    | '/profile'
    | '/run-schedulers'
    | '/sales-team'
    | '/samples'
    | '/settings'
    | '/shift'
    | '/support-tickets'
    | '/customer/$id'
    | '/officer/$id'
    | '/visits/$id'
    | '/visits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-customer'
    | '/adhoc-visits'
    | '/attendance'
    | '/city-management'
    | '/customers'
    | '/dashboard'
    | '/data-import'
    | '/export-data'
    | '/live-activity'
    | '/live-location'
    | '/live-shifts'
    | '/login'
    | '/missed-visits'
    | '/notifications'
    | '/payroll'
    | '/products'
    | '/profile'
    | '/run-schedulers'
    | '/sales-team'
    | '/samples'
    | '/settings'
    | '/shift'
    | '/support-tickets'
    | '/customer/$id'
    | '/officer/$id'
    | '/visits/$id'
    | '/visits'
  id:
    | '__root__'
    | '/'
    | '/add-customer'
    | '/adhoc-visits'
    | '/attendance'
    | '/city-management'
    | '/customers'
    | '/dashboard'
    | '/data-import'
    | '/export-data'
    | '/live-activity'
    | '/live-location'
    | '/live-shifts'
    | '/login'
    | '/missed-visits'
    | '/notifications'
    | '/payroll'
    | '/products'
    | '/profile'
    | '/run-schedulers'
    | '/sales-team'
    | '/samples'
    | '/settings'
    | '/shift'
    | '/support-tickets'
    | '/customer/$id'
    | '/officer/$id'
    | '/visits/$id'
    | '/visits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddCustomerRoute: typeof AddCustomerRoute
  AdhocVisitsRoute: typeof AdhocVisitsRoute
  AttendanceRoute: typeof AttendanceRoute
  CityManagementRoute: typeof CityManagementRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DataImportRoute: typeof DataImportRoute
  ExportDataRoute: typeof ExportDataRoute
  LiveActivityRoute: typeof LiveActivityRoute
  LiveLocationRoute: typeof LiveLocationRoute
  LiveShiftsRoute: typeof LiveShiftsRoute
  LoginRoute: typeof LoginRoute
  MissedVisitsRoute: typeof MissedVisitsRoute
  NotificationsRoute: typeof NotificationsRoute
  PayrollRoute: typeof PayrollRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  RunSchedulersRoute: typeof RunSchedulersRoute
  SalesTeamRoute: typeof SalesTeamRoute
  SamplesRoute: typeof SamplesRoute
  SettingsRoute: typeof SettingsRoute
  ShiftRoute: typeof ShiftRoute
  SupportTicketsRoute: typeof SupportTicketsRoute
  CustomerIdRoute: typeof CustomerIdRoute
  OfficerIdRoute: typeof OfficerIdRoute
  VisitsIdRoute: typeof VisitsIdRoute
  VisitsIndexRoute: typeof VisitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-customer': {
      id: '/add-customer'
      path: '/add-customer'
      fullPath: '/add-customer'
      preLoaderRoute: typeof AddCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adhoc-visits': {
      id: '/adhoc-visits'
      path: '/adhoc-visits'
      fullPath: '/adhoc-visits'
      preLoaderRoute: typeof AdhocVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city-management': {
      id: '/city-management'
      path: '/city-management'
      fullPath: '/city-management'
      preLoaderRoute: typeof CityManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-import': {
      id: '/data-import'
      path: '/data-import'
      fullPath: '/data-import'
      preLoaderRoute: typeof DataImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-data': {
      id: '/export-data'
      path: '/export-data'
      fullPath: '/export-data'
      preLoaderRoute: typeof ExportDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-activity': {
      id: '/live-activity'
      path: '/live-activity'
      fullPath: '/live-activity'
      preLoaderRoute: typeof LiveActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-location': {
      id: '/live-location'
      path: '/live-location'
      fullPath: '/live-location'
      preLoaderRoute: typeof LiveLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-shifts': {
      id: '/live-shifts'
      path: '/live-shifts'
      fullPath: '/live-shifts'
      preLoaderRoute: typeof LiveShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missed-visits': {
      id: '/missed-visits'
      path: '/missed-visits'
      fullPath: '/missed-visits'
      preLoaderRoute: typeof MissedVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run-schedulers': {
      id: '/run-schedulers'
      path: '/run-schedulers'
      fullPath: '/run-schedulers'
      preLoaderRoute: typeof RunSchedulersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-team': {
      id: '/sales-team'
      path: '/sales-team'
      fullPath: '/sales-team'
      preLoaderRoute: typeof SalesTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift': {
      id: '/shift'
      path: '/shift'
      fullPath: '/shift'
      preLoaderRoute: typeof ShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-tickets': {
      id: '/support-tickets'
      path: '/support-tickets'
      fullPath: '/support-tickets'
      preLoaderRoute: typeof SupportTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$id': {
      id: '/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof CustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/$id': {
      id: '/officer/$id'
      path: '/officer/$id'
      fullPath: '/officer/$id'
      preLoaderRoute: typeof OfficerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/': {
      id: '/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof VisitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits/$id': {
      id: '/visits/$id'
      path: '/visits/$id'
      fullPath: '/visits/$id'
      preLoaderRoute: typeof VisitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddCustomerRoute: AddCustomerRoute,
  AdhocVisitsRoute: AdhocVisitsRoute,
  AttendanceRoute: AttendanceRoute,
  CityManagementRoute: CityManagementRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DataImportRoute: DataImportRoute,
  ExportDataRoute: ExportDataRoute,
  LiveActivityRoute: LiveActivityRoute,
  LiveLocationRoute: LiveLocationRoute,
  LiveShiftsRoute: LiveShiftsRoute,
  LoginRoute: LoginRoute,
  MissedVisitsRoute: MissedVisitsRoute,
  NotificationsRoute: NotificationsRoute,
  PayrollRoute: PayrollRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  RunSchedulersRoute: RunSchedulersRoute,
  SalesTeamRoute: SalesTeamRoute,
  SamplesRoute: SamplesRoute,
  SettingsRoute: SettingsRoute,
  ShiftRoute: ShiftRoute,
  SupportTicketsRoute: SupportTicketsRoute,
  CustomerIdRoute: CustomerIdRoute,
  OfficerIdRoute: OfficerIdRoute,
  VisitsIdRoute: VisitsIdRoute,
  VisitsIndexRoute: VisitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
